apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: 561798357756.dkr.ecr.us-east-1.amazonaws.com/upwork-api:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
---