apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api-config
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-1.mongo/upwork"
  SERVER_PORT: "8080"
